// <auto-generated />
namespace HF_Application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _01121417 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_01121417));
        
        string IMigrationMetadata.Id
        {
            get { return "201712011317346_01121417"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
